CREATE TABLE TB_CP_MOVIE (
    NM_MOVIE VARCHAR(200),
	DS_GENRE VARCHAR(50),
	NM_DIRECTOR VARCHAR(50),
	DS_MOVIE VARCHAR (2000),
	TM_DURATION NUMBER(3),
    CD_MOVIE NUMBER(10,0) PRIMARY KEY,
	NR_RATING NUMBER(1)
);

CREATE SEQUENCE SQ_TB_CP_MOVIE START WITH 1 INCREMENT BY 1;

ALTER TABLE TB_CP_MOVIE MODIFY (NM_MOVIE CONSTRAINT CK_CP_MOVIE_NM_NN NOT NULL);
ALTER TABLE TB_CP_MOVIE MODIFY (DS_GENRE CONSTRAINT CK_CP_MOVIE_GR_NN NOT NULL);
ALTER TABLE TB_CP_MOVIE MODIFY (NM_DIRECTOR CONSTRAINT CK_CP_MOVIE_DR_NN NOT NULL);
ALTER TABLE TB_CP_MOVIE MODIFY (TM_DURATION CONSTRAINT CK_CP_MOVIE_DU_NN NOT NULL);
ALTER TABLE TB_CP_MOVIE MODIFY (CD_MOVIE CONSTRAINT CK_CP_MOVIE_CD_NN NOT NULL);

ALTER TABLE TB_CP_MOVIE ADD CONSTRAINT CK_CP_MOVIE_RATING CHECK (NR_RATING IN ('1', '2', '3', '4', '5'));